server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d8ho0vldt1ts73egrhdg-a.oregon-postgres.render.com:5432/cineflow_ccpu?sslmode=require
    username: cineflow_ccpu_user
    password: 3YPEoRRMWfM1KsjTEPcIAhvnSeBwlIir
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Voltou para update para manter os teus dados salvos
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always